version: '3.7'

services:
  web:
    build: ./
    command: python run.py
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      - TZ=Asia/Taipei
  db:
    image: postgres:12.0-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=caten_music

volumes:
    postgres_data:
