"""empty message

Revision ID: 0ffd68754a8a
Revises: 88d6a993aa3a
Create Date: 2019-05-29 21:17:12.599188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ffd68754a8a'
down_revision = '88d6a993aa3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_lists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_lists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('songs_sid_list', postgresql.ARRAY(sa.VARCHAR(length=8)), autoincrement=False, nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('edited_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('songs_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='song_lists_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='song_lists_pkey'),
    sa.UniqueConstraint('list_id', name='song_lists_list_id_key')
    )
    # ### end Alembic commands ###
