"""empty message

Revision ID: 553a666a821f
Revises: 737048117cae
Create Date: 2019-06-10 23:42:33.739453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '553a666a821f'
down_revision = '737048117cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songlists', 'songs_description_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songlists', sa.Column('songs_description_list', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
