"""empty message

Revision ID: 5bed936f5177
Revises: 
Create Date: 2019-05-01 11:42:32.346626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bed936f5177'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profile', sa.Column('sex', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_profile', 'sex')
    # ### end Alembic commands ###
