"""empty message

Revision ID: 88d6a993aa3a
Revises: 5bed936f5177
Create Date: 2019-05-26 23:32:19.418352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d6a993aa3a'
down_revision = '5bed936f5177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_lists', sa.Column('songs_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song_lists', 'songs_amount')
    # ### end Alembic commands ###
