"""empty message

Revision ID: 926ce5f75aef
Revises: 0ffd68754a8a
Create Date: 2019-05-29 22:04:11.523311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926ce5f75aef'
down_revision = '0ffd68754a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songlists', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('songlists', 'discription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songlists', sa.Column('discription', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('songlists', 'description')
    # ### end Alembic commands ###
