"""add invitation codes

Revision ID: bcfc6041a78f
Revises: e4bdcdd9ef5c
Create Date: 2025-03-12 09:07:17.378686

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bcfc6041a78f'
down_revision = 'e4bdcdd9ef5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'invitation_codes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('is_disabled', sa.Boolean(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['public.users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
        schema='public',
    )
    op.drop_constraint('song_reports_user_id_fkey', 'song_reports', type_='foreignkey')
    op.create_foreign_key(
        'song_reports_user_id_fkey',
        'song_reports',
        'users',
        ['user_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
    )
    op.drop_constraint('songlists_user_id_fkey', 'songlists', type_='foreignkey')
    op.create_foreign_key(
        'songlists_user_id_fkey',
        'songlists',
        'users',
        ['user_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
    )
    op.drop_constraint('users_profile_user_id_fkey', 'users_profile', type_='foreignkey')
    op.create_foreign_key(
        'users_profile_user_id_fkey',
        'users_profile',
        'users',
        ['user_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_profile_user_id_fkey', 'users_profile', schema='public', type_='foreignkey')
    op.create_foreign_key('users_profile_user_id_fkey', 'users_profile', 'users', ['user_id'], ['id'])
    op.drop_constraint('songlists_user_id_fkey', 'songlists', schema='public', type_='foreignkey')
    op.create_foreign_key('songlists_user_id_fkey', 'songlists', 'users', ['user_id'], ['id'])
    op.drop_constraint('song_reports_user_id_fkey', 'song_reports', schema='public', type_='foreignkey')
    op.create_foreign_key('song_reports_user_id_fkey', 'song_reports', 'users', ['user_id'], ['id'])
    op.drop_table('invitation_codes', schema='public')
    # ### end Alembic commands ###
