"""empty message

Revision ID: eb0590007e01
Revises: b3d1f14e70cf
Create Date: 2019-06-15 20:14:35.281699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0590007e01'
down_revision = 'b3d1f14e70cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_time')
    # ### end Alembic commands ###
