from typing import Protocol

from app.core.entities.invitation_code import InvitationCode


class InvitationRepository(Protocol):
    async def get_by_id(self, code_id: int) -> InvitationCode | None: ...
    async def get_by_code(self, code: str) -> InvitationCode | None: ...
    async def create(self, invitation: InvitationCode) -> InvitationCode: ...
    async def update(self, invitation: InvitationCode) -> InvitationCode: ...
    async def list_all(self) -> list[InvitationCode]: ...
