from typing import Protocol

from app.core.entities.songlist import SongList


class SonglistRepository(Protocol):
    async def get_by_out_id(self, out_id: str) -> SongList | None: ...
    async def get_by_user_id(self, user_id: int) -> list[SongList]: ...
    async def create(self, songlist: SongList) -> SongList: ...
    async def update(self, songlist: SongList) -> SongList: ...
    async def delete(self, songlist_id: int) -> None: ...
