from typing import Any, Protocol


class SongApiClient(Protocol):
    async def search(
        self,
        title: str = '',
        lyrics: str = '',
        lang: str = '',
        collection: str = '',
        tonality: str = '',
    ) -> list[dict[str, Any]]: ...

    async def get_by_sid(self, sid: str) -> list[dict[str, Any]]: ...
    async def get_by_sids(self, sids: list[str]) -> list[dict[str, Any]]: ...
    async def get_random(self, amount: int) -> list[dict[str, Any]]: ...
    async def create_song(self, data: dict[str, Any]) -> str: ...
    async def update_song(self, sid: str, data: dict[str, Any]) -> bool: ...
