from typing import Protocol


class TokenService(Protocol):
    def create_access_token(self, user_id: int) -> str: ...
    def create_refresh_token(self, user_id: int) -> str: ...
    def decode_token(self, token: str) -> dict | None: ...
    def create_activation_token(self, user_id: int) -> str: ...
    def create_password_reset_token(self, user_id: int) -> str: ...
    def verify_purpose_token(self, token: str, purpose: str) -> dict | None: ...
