from typing import Protocol

from app.core.entities.user import User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: int) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def create(self, user: User) -> User: ...
    async def update(self, user: User) -> User: ...
    async def exists_username(self, username: str) -> bool: ...
    async def exists_email(self, email: str) -> bool: ...
    async def list_all(self) -> list[User]: ...
